name: "godot build"
on: push

env:
    GODOT_VERSION: 4.2.2
    EXPORT_NAME: LastStand

jobs:
    export:
        name: Export Project
        runs-on: ubuntu-latest
        container:
            image: barichello/godot-ci:4.2.2
        strategy:
            matrix:
                target:
                    - platform: "web"
                      path: "index.html"
                    - platform: "windows"
                      path: "${EXPORT_NAME}.exe"
                    - platform: "linux"
                      path: "${EXPORT_NAME}.x86_64"
                    - platform: "macos"
                      path: "${EXPORT_NAME}.zip"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Copy Export Templates
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
            - name: Export
              run: |
                mkdir -v -p build
                godot --headless --verbose --export-release "${{ matrix.target.platform }}" build/${{ matrix.target.path }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.target.platform }}
                path: build
    deploy-pages:
        name: Deploy to Pages
        runs-on: ubuntu-latest
        needs: export
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download Web Build
              uses: actions/download-artifact@v4
              with:
                name: web
                path: web
            - name: Add coi-serviceworker for Pages
              run: |
                apt-get update && apt-get install -y curl
                curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.min.js > web/coi-serviceworker.min.js
                sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.min.js"></script>\n\1#' web/index.html
            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: web
            - name: Deploy to Pages
              id: deployment
              uses: actions/deploy-pages@v4
